#!/bin/sh
mkdir -p /tmp/images
chmod 777 /tmp/images
mkdir -p /greengrass/certs
mkdir -p /greengrass/config
cp /boot/certs/* /greengrass/certs/
cp /boot/config/* /greengrass/config/
/greengrass/ggc/core/greengrassd \$@
